name: Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    strategy:
      matrix:
        model_type:
          [
            "openpose",
            "seg",
            "scribble",
            "mlsd",
            "normal",
            "mlsd",
            "normal",
            "hed",
            "depth",
            "canny",
          ]

    runs-on: ubuntu-latest
    steps:
      - name: Clear Space
        run: |
          rm -rf /usr/share/dotnet
          rm -rf /opt/ghc
          rm -rf "/usr/local/share/boost"
          rm -rf "$AGENT_TOOLSDIRECTORY"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          build-args: MODEL_TYPE=${{ matrix.model_type }}
          push: true
          tags: ${{ secrets.DOCKERHUB_REPO }}/${{ secrets.DOCKERHUB_IMG }}:dev
